sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: fTx3T/ocB7LtjKzj1hLvn1tbG/UJTqr3y2MeR4Zqx13tVUVGvRBCy9yV0vYuBhtglCvOLVxrnbFbPJkbXYhlulHdfedvBPMWCDw+Kyaje3jL/vGjsCBDHi4xb04rbwcF4VaBn5I8lSAN5udTrAQLtdeLg8GuygeARrxo+ov5lzYHjB/8MXt2K8f5YgsTkAqGgqRl+OlPWmwl+u+gDfo2mgj+7wbDmTAzCeLlsu4cW8rtYPJOtjzm1DyN/z0Vw7qx1bxkYyYP344pvp78s/Sw+euiY9oBxe4kKv2p2Ni1GyRFtwM+ODOzQCXxz0M0/1o7gYeMOO32IE21uoYt0FmE3Pd8tJH6xERCMfdo3S/mxMno3LKi6sxIkzwW5F21q/bmTqLWLwfXRqzrZ4zGRuKu6bFkQFc1B519waCy1QJjcisyGkhZgzsPVfKwUw7W7DOjH0rK9xMln+4B+QMtKL1I+2pXzVT/3K2w5A0zt3r4FvoO0/Lqneao6m6/1TU8AtJjcA4gNRAvJXvf8Z9FRoDFkuF7LcE1Jh5Kmc8eJ6+Wn+04eVAVYTrfU1N7qYpxJP89t9iCf5kWNElgyW9PB5plMree1TYfo5p7SZ4leog5J1MptGSJGjz25hNtoNtUq5wzZxINmiszr7Uw401V6F98/cVFYm35jqnVNO2MaGRQU9Q=
  only:
  - master
dd:
  secure: hqTmNIHqjL4Hn40RRrTW4oZSrMPODjfc0cmo9ilzSoOFAvZOJyJIhUPwzAAbhEOoXvXtlZzOG9ykxK3lJgBR1/KUDyf29dChPL5NoPHZl+Xj7yQRifxxalUlifaH60k6Zgb5cNqBuHop+vr03psQGaLqkYV61sRW3y9f6dIXvcF+y1fLnQe82VLaeGY+STtOpP9kIkTq9Rfop78bS560Mq9xyDI3j6bYBQKXhJcG2Z8eB7USeSFQxg4voUXFfD4IUoMoOcXEeJTPdj5iDgPrNwizLiq7dacob7EfjNuUtFLuW7gbSZ+0v8C3KI8cCpPX+zORFD9FiHY7eI/j2N9lCRaDvuiLNAxCQ7M7Ymb1HO6CVe1ifD1RNHvvF14BbyqzEdZc+wr1ygNeWfuK8+vrgU3lHxCmUbO5sNWF6YQ11eEmYEMuq2OvaDw9zPhzp7ECOTVMTjW+AyB7WNFjbV01FzdBlsvmmAX6s4kgyhfEvNEI+L3TixUGmxXngFZZujOoJ7twOhB5TS9MEfLeP87tKTs6NeqH5yJ19DVcLT/4kfWxEO7eN6YajspxHWkO3FmAd9gQ3zY341IocioYqCQkaJdFrnVIbZ2lddnOqi9ZQv8jRcGhkJWfvcftVpKE4Uzi3DUZfgUn+HQmvnz27RVMiqlz5rN8ZkfI9/urHT8vi2I=
