sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: fTx3T/ocB7LtjKzj1hLvn1tbG/UJTqr3y2MeR4Zqx13tVUVGvRBCy9yV0vYuBhtglCvOLVxrnbFbPJkbXYhlulHdfedvBPMWCDw+Kyaje3jL/vGjsCBDHi4xb04rbwcF4VaBn5I8lSAN5udTrAQLtdeLg8GuygeARrxo+ov5lzYHjB/8MXt2K8f5YgsTkAqGgqRl+OlPWmwl+u+gDfo2mgj+7wbDmTAzCeLlsu4cW8rtYPJOtjzm1DyN/z0Vw7qx1bxkYyYP344pvp78s/Sw+euiY9oBxe4kKv2p2Ni1GyRFtwM+ODOzQCXxz0M0/1o7gYeMOO32IE21uoYt0FmE3Pd8tJH6xERCMfdo3S/mxMno3LKi6sxIkzwW5F21q/bmTqLWLwfXRqzrZ4zGRuKu6bFkQFc1B519waCy1QJjcisyGkhZgzsPVfKwUw7W7DOjH0rK9xMln+4B+QMtKL1I+2pXzVT/3K2w5A0zt3r4FvoO0/Lqneao6m6/1TU8AtJjcA4gNRAvJXvf8Z9FRoDFkuF7LcE1Jh5Kmc8eJ6+Wn+04eVAVYTrfU1N7qYpxJP89t9iCf5kWNElgyW9PB5plMree1TYfo5p7SZ4leog5J1MptGSJGjz25hNtoNtUq5wzZxINmiszr7Uw401V6F98/cVFYm35jqnVNO2MaGRQU9Q=
  only:
  - master
dd:
  secure: uNBDBkaE7NlQfBU+YpXvpv16EYaflaxy0fQ1PCnoYrDwqI1LCSPZ7z5JnzXvC0JTH1P0U/UlnBHTNt9vHmugvfHTex6k7dBz0qsY01bjqGkEz9eRr+IHOp735eFk2zMWM3di3pvbxw+qHOdlnygQMZQ5zfVuu3N3CqEZWT6LIZfFcTdpuvYyIwZdX/iFSkm8ZVZnT2ZTUCLWrUZWmF5S74Zz1iB/7SXMtD+gkhkNHHxJkwu79BrsIjoPjwV+pxwwYUCUygdPmeJJr09HpWADghhKhwad/ieqIKKPJPvQmJJULg+k5MHuzPWa00RVA5dNTaItneG3LISjwgLN5OJCOkMspnbZRRfjFAzXtrH0ndf0N0b0rJIdPNYkOrqlHFntwtL02Gkv1P+ymG/VxHj4epYcTdiNdqOLYWGhMpvjMAmlFirR/aBsgFiG78rB4rozp4kAERAnkMr5aB/4C6hiGJXTcHvSQtV4hu3k/bFlu4Yj9enJAjMcKvN3cjYM2rgFrXZviSDUIIb0iVZU7GSf9S4Qu2gMIPtzbVTc4+OJ/7LqPWEH1GkOmRIUQobjNy7RBmE6BrZBpffoPgpWMNwwxFy7BTXwJInuYubQo1t3/W7Qi1ZU5J2GZT9YNR+NaCJU56GayHGCZ/PrXdSHk5ehfiAjNL3dPWemW6Dhghp62y0=
