sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: fTx3T/ocB7LtjKzj1hLvn1tbG/UJTqr3y2MeR4Zqx13tVUVGvRBCy9yV0vYuBhtglCvOLVxrnbFbPJkbXYhlulHdfedvBPMWCDw+Kyaje3jL/vGjsCBDHi4xb04rbwcF4VaBn5I8lSAN5udTrAQLtdeLg8GuygeARrxo+ov5lzYHjB/8MXt2K8f5YgsTkAqGgqRl+OlPWmwl+u+gDfo2mgj+7wbDmTAzCeLlsu4cW8rtYPJOtjzm1DyN/z0Vw7qx1bxkYyYP344pvp78s/Sw+euiY9oBxe4kKv2p2Ni1GyRFtwM+ODOzQCXxz0M0/1o7gYeMOO32IE21uoYt0FmE3Pd8tJH6xERCMfdo3S/mxMno3LKi6sxIkzwW5F21q/bmTqLWLwfXRqzrZ4zGRuKu6bFkQFc1B519waCy1QJjcisyGkhZgzsPVfKwUw7W7DOjH0rK9xMln+4B+QMtKL1I+2pXzVT/3K2w5A0zt3r4FvoO0/Lqneao6m6/1TU8AtJjcA4gNRAvJXvf8Z9FRoDFkuF7LcE1Jh5Kmc8eJ6+Wn+04eVAVYTrfU1N7qYpxJP89t9iCf5kWNElgyW9PB5plMree1TYfo5p7SZ4leog5J1MptGSJGjz25hNtoNtUq5wzZxINmiszr7Uw401V6F98/cVFYm35jqnVNO2MaGRQU9Q=
  only:
  - master
dd:
  secure: ZEZzefymR0MqDqdk9ZpgAS6qIXaUVHRN6ad2OkYqVaCdRhmbjhAKFjxRltLFe+cGLTvPjr6vPZVDIvlgnTHRf9iJ88ysOI3BYhNEm3+tia9/Ktla7FQbGr4meQwud5oK6zXVfY1smweviCwZ3DiLCmMk114xWSiLepagqyK5JpmVFNVV0xtpS1AvJVofwsWUA3e2ho7pzXkSP0rUHgJHdZcouCvmdcnry/KV1rNdmJcVnjWyusuHPZJFFY/EHFN51Y09/x5dlxgCw0MQYJk6wet/QrSYzjuWBje3vW65Xb1mXUC3HAJJyTPtwYWHMQvs7SAO1VrO996nyUBE7vaYS6mMLY4FSRAy8y31kG41e6Dx9L9zK8qGXq8uSbw76sDzv9M6JD9fUnz7O9oHxZBG0rlMBI9gHooprmlScqQVXgfL3PajVJaomrQvmbNTstKRc9liXv5Q0OrSvtHiL3VBZoVmxxjOGhAwPmqnme5Ov4LVpDsMM3SX3ncD2gOKQDtie5GI5sog3ED23IAqMxjdzlJNaNp7Yc54ysmUTvQxwReXzQDRapyaPnYLzs7LV4AVSbYvk+R3BsKJNWTPl9PbnjFq14+R/Sz1Wo8LHw/lxwtbIhbFEqXF+fzNRnn2Rm0g/zL4tKiDqEWoRR3/i1C6DbEC4ua1O8XD9UkHrYBtAuU=
