sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
before_script:
  - npm install -g firebase-tools
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: hqTmNIHqjL4Hn40RRrTW4oZSrMPODjfc0cmo9ilzSoOFAvZOJyJIhUPwzAAbhEOoXvXtlZzOG9ykxK3lJgBR1/KUDyf29dChPL5NoPHZl+Xj7yQRifxxalUlifaH60k6Zgb5cNqBuHop+vr03psQGaLqkYV61sRW3y9f6dIXvcF+y1fLnQe82VLaeGY+STtOpP9kIkTq9Rfop78bS560Mq9xyDI3j6bYBQKXhJcG2Z8eB7USeSFQxg4voUXFfD4IUoMoOcXEeJTPdj5iDgPrNwizLiq7dacob7EfjNuUtFLuW7gbSZ+0v8C3KI8cCpPX+zORFD9FiHY7eI/j2N9lCRaDvuiLNAxCQ7M7Ymb1HO6CVe1ifD1RNHvvF14BbyqzEdZc+wr1ygNeWfuK8+vrgU3lHxCmUbO5sNWF6YQ11eEmYEMuq2OvaDw9zPhzp7ECOTVMTjW+AyB7WNFjbV01FzdBlsvmmAX6s4kgyhfEvNEI+L3TixUGmxXngFZZujOoJ7twOhB5TS9MEfLeP87tKTs6NeqH5yJ19DVcLT/4kfWxEO7eN6YajspxHWkO3FmAd9gQ3zY341IocioYqCQkaJdFrnVIbZ2lddnOqi9ZQv8jRcGhkJWfvcftVpKE4Uzi3DUZfgUn+HQmvnz27RVMiqlz5rN8ZkfI9/urHT8vi2I=
  only:
  - develop
dd:
  secure: hqTmNIHqjL4Hn40RRrTW4oZSrMPODjfc0cmo9ilzSoOFAvZOJyJIhUPwzAAbhEOoXvXtlZzOG9ykxK3lJgBR1/KUDyf29dChPL5NoPHZl+Xj7yQRifxxalUlifaH60k6Zgb5cNqBuHop+vr03psQGaLqkYV61sRW3y9f6dIXvcF+y1fLnQe82VLaeGY+STtOpP9kIkTq9Rfop78bS560Mq9xyDI3j6bYBQKXhJcG2Z8eB7USeSFQxg4voUXFfD4IUoMoOcXEeJTPdj5iDgPrNwizLiq7dacob7EfjNuUtFLuW7gbSZ+0v8C3KI8cCpPX+zORFD9FiHY7eI/j2N9lCRaDvuiLNAxCQ7M7Ymb1HO6CVe1ifD1RNHvvF14BbyqzEdZc+wr1ygNeWfuK8+vrgU3lHxCmUbO5sNWF6YQ11eEmYEMuq2OvaDw9zPhzp7ECOTVMTjW+AyB7WNFjbV01FzdBlsvmmAX6s4kgyhfEvNEI+L3TixUGmxXngFZZujOoJ7twOhB5TS9MEfLeP87tKTs6NeqH5yJ19DVcLT/4kfWxEO7eN6YajspxHWkO3FmAd9gQ3zY341IocioYqCQkaJdFrnVIbZ2lddnOqi9ZQv8jRcGhkJWfvcftVpKE4Uzi3DUZfgUn+HQmvnz27RVMiqlz5rN8ZkfI9/urHT8vi2I=
